source 'http://rubygems.org'

gem 'faraday', '~> 2.0', '< 3.0'
gem 'rake', '~> 13'
gem 'rspec'
gem 'rspec_junit_formatter'
gem 'rspec-rails'

if ENV['X_PACT_DEVELOPMENT']
  gem 'pact', path: '../../pact-ruby'
  gem 'pact-ffi', path: '../../pact-ruby-ffi'
else
  gem 'pact'
  gem 'pact-ffi', '~> 0.4.28'
end
# for pact v2 support helpers (activesupport)
gem 'combustion'
# for provider verification
gem 'webmock'
# kafka gems - no support on windows
unless RUBY_PLATFORM =~ /win32|x64-mingw32|x64-mingw-ucrt/
  gem "sbmt-kafka_consumer", ">= 2.0.1"
  gem "sbmt-kafka_producer", ">= 1.0"
end
if ENV['X_PACT_DEVELOPMENT_RDKAFKA'] == 'true'
  # darwin-arm64 prebuilt gems available from 0.20.0
  gem.add_development_dependency "karafka-rdkafka", ">= 0.20.0"
end 
# required in pact v2 on windows
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
# for grpc transport / protobuf content
gem 'gruf', '>= 2.18'
gem 'gruf-rspec', '>= 0.6.0'
