source 'http://rubygems.org'

gem 'faraday', '~> 1.0', '< 3.0'
gem 'gruf', '>= 2.18'
gem 'gruf-rspec', '>= 0.6.0'
gem 'rake', '~> 13'
gem 'rspec'
gem 'rspec_junit_formatter'
gem 'rspec-rails'
if ENV['X_PACT_DEVELOPMENT']
  gem 'pact', path: '../pact-ruby'
else
  gem 'pact', git: 'https://github.com/pact-foundation/pact-ruby.git', branch: 'feat/v2'
end
gem 'combustion'
gem 'webmock'
unless RUBY_PLATFORM =~ /win32|x64-mingw32|x64-mingw-ucrt/
  gem "sbmt-kafka_consumer", ">= 2.0.1"
  gem "sbmt-kafka_producer", ">= 1.0"
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
# todo rm
# gem "karafka-rdkafka", ">= 0.20.0"