source 'http://rubygems.org'

gem 'combustion'
gem 'faraday', '~> 1.0', '< 3.0'
gem 'rake', '~> 13'
gem 'rspec'
gem 'rspec-rails'
if ENV['X_PACT_DEVELOPMENT']
  gem 'pact', path: '../pact-ruby'
else
  gem 'pact', git: 'https://github.com/pact-foundation/pact-ruby.git', branch: 'feat/v2'
end
gem 'webmock'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
