require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new('pact:spec') do |task|
  task.pattern = 'spec/pact/providers/**/*_spec.rb'
  task.rspec_opts = ['-t pact']
end

require 'pact_broker/client/tasks'

PactBroker::Client::PublicationTask.new do | task |
  task.auto_detect_version_properties = true
  task.pattern = 'spec/pacts/*.json' # optional, default value is 'spec/pacts/*.json'
  
  task.pact_broker_base_url = "http://localhost:9292"
  # task.pact_broker_base_url = "https://testdemo.pactflow.io"
  # task.pact_broker_basic_auth =  { username: 'basic_auth_user', password: 'basic_auth_pass'} # optional
  # task.pact_broker_token = "1234abcd" # Bearer token.
end