source 'http://rubygems.org'


gem 'rake', '~> 13'

## for pact
gem 'rspec'
if ENV['X_PACT_DEVELOPMENT']
  gem 'pact', path: '../pact-ruby'
else
  gem 'pact'
end
gem 'combustion'
gem 'webmock'

## for grpc
gem 'gruf', '>= 2.18'
gem 'gruf-rspec', '>= 0.6.0'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
