source 'http://rubygems.org'

if ENV['X_PACT_DEVELOPMENT']
  gem 'pact', path: '../pact-ruby'
else
  gem 'pact', git: 'https://github.com/pact-foundation/pact-ruby.git', branch: 'feat/v2'
end

gem 'combustion'
gem 'rspec-rails'
gem 'webmock'

gem 'faraday'
gem 'pact_broker-client'
gem 'pry-byebug'
gem 'rake'
gem 'rspec'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
