source "https://rubygems.org"

group :development, :test do

  gem 'pry'

  gem 'rspec'

  gem 'pact-message'

  gem 'rake'
  if ENV['X_PACT_DEVELOPMENT']
    gem 'pact', path: '../pact-ruby'
  else
    gem 'pact', git: 'https://github.com/pact-foundation/pact-ruby.git', branch: 'feat/v2'
  end
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
  gem 'combustion'
  gem 'webmock'

end