# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
require 'pact/tasks'

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new('pact:v2:spec') do |task|
  task.pattern = 'spec/pact/providers/**/*_spec.rb'
  task.rspec_opts = ['-t pact_v2', '--require pact_v2_helper']
end
RSpec::Core::RakeTask.new('pact:spec') do |task|
  task.pattern = 'spec/consumer_spec.rb'
  task.rspec_opts = ['-t pact']
end

RSpec::Core::RakeTask.new('pact:v2:verify') do |task|
  task.pattern = 'spec/pact/consumers/**/*_spec.rb'
  task.rspec_opts = ['-t pact_v2', '--require pact_v2_helper']
end
