require 'pact/tasks/verification_task'
require 'pact_broker/client/tasks'
require 'pact/tasks'

LOCAL_PACT_BROKER_BASE_URL = 'http://localhost:9292'
REMOTE_PACT_BROKER_BASE_URL = 'https://test.pactflow.io'

# These pact publication tasks would normally be in the consumer codebase,
# but they're here so we can run the entire consumer/provider flow with one rake command.
PactBroker::Client::PublicationTask.new(:local) do | task |
  task.consumer_version = "1.0.0"
  task.pact_broker_base_url = LOCAL_PACT_BROKER_BASE_URL,
  task.pattern = "consumer/spec/pacts/*.json"
end

PactBroker::Client::PublicationTask.new(:remote) do | task |
  task.consumer_version = "1.0.0"
  task.pact_broker_base_url = REMOTE_PACT_BROKER_BASE_URL
  task.tags = %w{production master}
  task.pact_broker_basic_auth =  { username: 'dXfltyFMgNOFZAxr8io9wJ37iUpY42M', password: 'O5AIZWxelWbLvqMd8PkAVycBJh2Psyg1'}
  task.pattern = "consumer/spec/pacts/*.json"
end

Pact::VerificationTask.new(:foobar) do | pact |
  pact.uri './consumer/spec/pacts/foo-bar.json', pact_helper: './provider/spec/pact_helper.rb'
end

Pact::VerificationTask.new(:foobar_using_local_broker) do | pact |
  pact.uri "#{LOCAL_PACT_BROKER_BASE_URL}/pacts/provider/Bar/consumer/Foo/version/1.0.0", :pact_helper => './provider/spec/pact_helper.rb'
end

Pact::VerificationTask.new(:foobar_using_remote_broker) do | pact |
  pact.uri "#{REMOTE_PACT_BROKER_BASE_URL}/pacts/provider/Bar/consumer/Foo/version/1.0.0", :pact_helper => './provider/spec/pact_helper.rb'
end

task 'pact:set_publish_verification_results_flag' do
  ENV['PUBLISH_VERIFICATIONS_RESULTS'] = 'true'
end

task 'pact:verify:foobar_using_local_broker' => ['pact:set_publish_verification_results_flag', 'pact:publish:local']
task 'pact:verify:foobar_using_remote_broker' => ['pact:set_publish_verification_results_flag', 'pact:publish:remote']

task 'pact:bethtest' => ['pact:set_publish_verification_results_flag', 'pact:publish:remote', 'pact:verify']