name: "Test transport type: http/kafka/grpc/mixed"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]
        os: [ windows-latest, macos-13, macos-14, ubuntu-latest ]
        type: [http, kafka, grpc, message, mixed]
        exclude:
          - os: windows-latest
            type: kafka # no windows support for kafka gems
          - os: windows-latest
            type: mixed # need to skip kafka tests from mixed
    env:
      RUBY_VERSION: ${{ matrix.ruby }}
    name: Ruby ${{ matrix.ruby }}-${{ matrix.os }}-${{ matrix.type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby
        if: env.ACT == 'true' && runner.arch == 'ARM64'
        run: sudo apt-get update && apt-get install -y ruby-full ruby-bundler
      - name: Setup Ruby w/ same version as image
        if: env.ACT != 'true' && runner.arch != 'ARM64'
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: ${{ matrix.ruby }}
            bundler-cache: true
            working-directory: ${{ matrix.type }}
      - name: Install dependencies
        run: make install
        working-directory: ${{ matrix.type }}
      - name: Run tests
        run: make
        working-directory: ${{ matrix.type }}
