name: Test e2e/e2e-v1

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.2", "3.3", "3.4"]
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      # e2e - v1
      - run: "bundle install"
        working-directory: e2e-pact-ruby-v1
      - run: "bundle exec rake pact:spec"
        working-directory: e2e-pact-ruby-v1
      - run: "bundle exec rake pact:verify:foobar"
        working-directory: e2e-pact-ruby-v1
        if: matrix.os != 'windows-latest'
      # e2e - v2
      - run: "bundle install"
        working-directory: e2e
      - run: "bundle exec rake pact:spec"
        working-directory: e2e
      - run: "bundle exec rake pact:verify:foobar"
        working-directory: e2e
